
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertionEuroToMad", targetNamespace = "http://ws/", className = "ws.ConvertionEuroToMad")
    @ResponseWrapper(localName = "convertionEuroToMadResponse", targetNamespace = "http://ws/", className = "ws.ConvertionEuroToMadResponse")
    @Action(input = "http://ws/BanqueService/convertionEuroToMadRequest", output = "http://ws/BanqueService/convertionEuroToMadResponse")
    public double convertionEuroToMad(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "ws.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "ws.GetAccountResponse")
    @Action(input = "http://ws/BanqueService/getAccountRequest", output = "http://ws/BanqueService/getAccountResponse")
    public Compte getAccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAccounts", targetNamespace = "http://ws/", className = "ws.GetAllAccounts")
    @ResponseWrapper(localName = "getAllAccountsResponse", targetNamespace = "http://ws/", className = "ws.GetAllAccountsResponse")
    @Action(input = "http://ws/BanqueService/getAllAccountsRequest", output = "http://ws/BanqueService/getAllAccountsResponse")
    public List<Compte> getAllAccounts();

}
